# Specify a name for this workflow
name: CICD
# Run this workflow on pushes to master and pull requests into master
on:
  push
jobs:
  deploy:
    # Only deploy if the code was commited to master, not for PRs
    if: github.ref == 'refs/heads/master'
    # Note no container is specified, this job will run in the shell
    runs-on: [self-hosted, deploy]
    env:
      PORT: 8081
    steps:
      - uses: actions/checkout@v2
      # Grab the build artifact from the previous job
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: react-build
      - name: Redeploy
        run: |
          tar -xvf example-app.tar.gz
          docker-compose -p github up --force-recreate -d